language: python
python: 2.7
env:
  - TOXENV=py27-dj16
  - TOXENV=py27-dj17
  - TOXENV=py27-dj18
  - TOXENV=py27-dj19
  - TOXENV=py33-dj16
  - TOXENV=py33-dj17
  - TOXENV=py33-dj18
  - TOXENV=py33-dj19
  - TOXENV=py34-dj16
  - TOXENV=py34-dj17
  - TOXENV=py34-dj18
  - TOXENV=py34-dj19
  - TOXENV=py35-dj18
  - TOXENV=py35-dj19
install:
  - pip install tox
script:
  - tox
